import type { DefaultTheme } from 'styled-components';
import { border, minTapTarget, motion, radius, spacing, type } from './tokens';

export const lightTheme: DefaultTheme = {
  mode: 'light',
  colour: {
    bg: '#faf7f0',
    surface: '#ffffff',
    surfaceAlt: '#f3ede2',
    text: '#2a2420',
    textMuted: '#6e5c4b',
    hairline: '#e7ddcc',
    outline: '#85755f',
    accent: '#7a4b2a',
    onAccent: '#ffffff',
    focus: '#7a4b2a',
    indigo: '#1f3550',
    gold: '#b8892e',
    sage: '#5e7d4f',
    sageText: '#4e6b41',
    danger: '#a63a2b',
  },
  status: {
    ordered: { fg: '#5a4a3c', bg: '#efe8dc' },
    confirmed: { fg: '#3e5a31', bg: '#e4ecdd' },
    ready: { fg: '#6e4f12', bg: '#f6e9cc' },
    outForDelivery: { fg: '#1f3550', bg: '#dfe6ef' },
    cancelled: { fg: '#8a2e21', bg: '#f5e1dd' },
    done: { fg: '#5f5a52', bg: '#ece9e3' },
  },
  border,
  spacing,
  type,
  radius,
  motion,
  minTapTarget,
};

export const darkTheme: DefaultTheme = {
  mode: 'dark',
  colour: {
    bg: '#16120e',
    surface: '#211b15',
    surfaceAlt: '#2b241c',
    text: '#f3ece1',
    textMuted: '#bca98f',
    hairline: '#3a3027',
    outline: '#857460',
    accent: '#c68a57',
    onAccent: '#1a120b',
    focus: '#c68a57',
    indigo: '#a9bfdc',
    gold: '#d9ae57',
    sage: '#8fb07d',
    sageText: '#8fb07d',
    danger: '#e07c6c',
  },
  status: {
    ordered: { fg: '#d6c7b2', bg: '#2e271f' },
    confirmed: { fg: '#b9d3a9', bg: '#26321f' },
    ready: { fg: '#e8c77e', bg: '#3a2f17' },
    outForDelivery: { fg: '#b5c9e4', bg: '#1e2a3a' },
    cancelled: { fg: '#efa597', bg: '#3a1f1a' },
    done: { fg: '#bdb6aa', bg: '#2a2723' },
  },
  border,
  spacing,
  type,
  radius,
  motion,
  minTapTarget,
};
